### ISSUE TITLE
Progress-Feedback

### ISSUE THREAD

**Issue by NuhaKhaled** [Mosab-Mohamed/ezay#1]
I saw today your application!. I love your progress, yet as @Mosab-Mohamed wasn't there. I loved to give you feedback here again. :+1: !

My favorite team til now and the most team I care about his feedback about the course in the end.

Kindly try to push to any web-host like heroku, and I may start to add issues for you as well.  :smile: 

And also, if you got your own issues start to add it here for yourself to track so I won't be recommending stuff you are already working on.

**Comment by Mosab-Mohamed** [comment]
Thank u for your trust and encouragement we really appreciate that :D 
and if we have any issues we will not hesitate to add here :)

**Comment by AhmedKhFa** [comment]
We will try to push the project to heroku , thanks for your efforts :)
